FROM python:3.7-slim

WORKDIR /app
RUN mkdir data
 
# Копируем файлы проекта в контейнер.
COPY backend/. .
COPY data/ /app/data
# Выполняем установку зависимостей внутри контейнера.
# раскоментировать что бы собрать на маке
# RUN apt-get update \
#    && apt-get -y install libpq-dev gcc
RUN python3 -m pip install --upgrade pip setuptools
RUN pip3 install -r /app/requirements.txt --no-cache-dir

# Выполнить запуск сервера при старте контейнера.
CMD ["gunicorn", "backend.wsgi:application", "--bind", "0:8000", "--log-syslog"]
# CMD ["python3", "manage.py", "runserver", "8000"]
