version: '3.3'
services:

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  backend:
    build:
      context: ../
      dockerfile: backend/Dockerfile
    volumes:
      - static_data_admin:/app/static/admin/
      - static_data_drf:/app/static/rest_framework/
      - media_data:/app/media/  
    ports:
      - "8000:8000"
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media_data:/usr/share/nginx/html/media/
      - static_data_admin:/usr/share/nginx/html/static/admin/
      - static_data_drf:/usr/share/nginx/html/static/rest_framework/

volumes:
  db_data:
  static_data_admin:
  static_data_drf:
  media_data: