# Generated by Django 2.2.16 on 2022-10-17 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0002_auto_20221009_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'verbose_name': 'Ингридиент', 'verbose_name_plural': 'Ингридиенты'},
        ),
    ]
