# Generated by Django 2.2.16 on 2022-10-02 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0003_auto_20221002_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsrecipe',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='ingredientsrecipe',
            name='ingredients_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientsrecipe', to='foodgram.Ingredients', verbose_name='Ингридиент'),
        ),
        migrations.AlterField(
            model_name='ingredientsrecipe',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientsrecipe', to='foodgram.Recipe', verbose_name='Рецепт'),
        ),
    ]
