# Generated by Django 2.2.16 on 2022-10-02 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0004_auto_20221002_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsrecipe',
            name='ingredients_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IngredientsRecipe', to='foodgram.Ingredients', verbose_name='Ингридиент'),
        ),
        migrations.AlterField(
            model_name='ingredientsrecipe',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IngredientsRecipe', to='foodgram.Recipe', verbose_name='Рецепт'),
        ),
    ]
